package co.edu.uniquindio.agenciaserver.controllers;

public enum TipoPeticion {
	HACER_LOGIN, GUARDAR_CLIENTE, LISTAR_CLIENTE, ACTUALIZAR_CLIENTE, ELIMINAR_CLIENTE, BUSCAR_CLIENTE,
	VERIFICAR_CLIENTE, GUARDAR_DESTINO, LISTAR_DESTINO, ACTUALIZAR_DESTINO, ELIMINAR_DESTINO, BUSCAR_DESTINO,
	VERIFICAR_DESTINO, GUARDAR_GUIA, LISTAR_GUIA, ACTUALIZAR_GUIA, ELIMINAR_GUIA, BUSCAR_GUIA, VERIFICAR_GUIA,
	GUARDAR_IMAGEN, LISTAR_IMAGEN, ACTUALIZAR_IMAGEN, ELIMINAR_IMAGEN, BUSCAR_IMAGEN, VERIFICAR_IMAGEN, GUARDAR_PAQUETE,
	LISTAR_PAQUETE, ACTUALIZAR_PAQUETE, ELIMINAR_PAQUETE, BUSCAR_PAQUETE, VERIFICAR_PAQUETE, GUARDAR_RESERVA,
	LISTAR_RESERVA, ACTUALIZAR_RESERVA, ELIMINAR_RESERVA, BUSCAR_RESERVA, VERIFICAR_RESERVA, GUARDAR_ADMIN,
	LISTAR_ADMIN, ACTUALIZAR_ADMIN, ELIMINAR_ADMIN, BUSCAR_ADMIN, VERIFICAR_ADMIN, ENVIAR_PDF;
}
